#pragma kernel CullGrass

#define TWOPI 6.2831853

struct GrassData
{
    float3 position;
    float rotationY;
    float2 scale;
};

// Input
uint columns;
uint rows;
float2 grassSpacing;
float3 boundsSize;
float3 boundsCenter;
float2 baseGrassSize;
float2 grassSizeVariance;
float spawnHeight;
float randomOffset;
float3 cameraPosition;
float maxRenderDistance;
float4 frustumPlanes[6];

// Output
AppendStructuredBuffer<GrassData> visibleGrassBuffer;

uint pcg_hash(uint input)
{
    uint state = input * 747796405u + 2891336453u;
    uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
    return (word >> 22u) ^ word;
}

float hash(uint input)
{
    return saturate(float(pcg_hash(input)) / 4294967295.0);
}

[numthreads(64, 1, 1)]
void CullGrass(uint3 id : SV_DispatchThreadID)
{
    uint myIndex = id.x;
    if (myIndex >= columns * rows)
    {
        return;
    }

    // Calculate Grid Position
    uint gridX = myIndex % columns;
    uint gridY = myIndex / columns;

    float cellCenterX = boundsCenter.x - boundsSize.x * 0.5 + (float(gridX) + 0.5) * grassSpacing.x;
    float cellCenterZ = boundsCenter.z - boundsSize.z * 0.5 + (float(gridY) + 0.5) * grassSpacing.y;

    // Add Random Offset
    float offsetX = (hash(myIndex) - 0.5) * grassSpacing.x * randomOffset;
    float offsetZ = (hash(myIndex + 1337) - 0.5) * grassSpacing.y * randomOffset;

    float posX = cellCenterX + offsetX;
    float posY = spawnHeight + baseGrassSize.y + boundsCenter.y;
    float posZ = cellCenterZ + offsetZ;

    float3 pos = float3(posX, posY, posZ);

    // Distance Culling
    float dist = distance(pos, cameraPosition);
    if (dist > maxRenderDistance)
    {
        return;
    }

    // Frustum Culling
    float boundRadius = max(baseGrassSize.x + grassSizeVariance.x, baseGrassSize.y + grassSizeVariance.y);

    for (int i = 0; i < 6; i++)
    {
        float distanceFromPlane = dot(frustumPlanes[i].xyz, pos) + frustumPlanes[i].w;

        if (distanceFromPlane < -boundRadius)
        {
            return;
        }
    }

    // Append
    GrassData grass;
    grass.position = pos;
    grass.rotationY = TWOPI * hash(myIndex * 3);
    grass.scale = baseGrassSize + hash(myIndex * 5) * grassSizeVariance;

    visibleGrassBuffer.Append(grass);
}
