#pragma kernel UpdateBoids

#define DEG2RAD 0.0174532925

struct BoidData
{
    float3 position;
    float3 velocity;
    float3 forward;
    float3 up;
    float maxSpeed;
};

RWStructuredBuffer<BoidData> boidsBuffer;
RWStructuredBuffer<float4x4> transformBuffer;

uint numBoids;
float boidScale;
float deltaTime;
float accelerationForce;
float rotationalSharpness;
float bankMultiplier;

float separationDistanceSqr;
float alignmentDistanceSqr;
float cohesionDistanceSqr;

float separationWeight;
float alignmentWeight;
float cohesionWeight;

float3 boundsCenter;
float3 boundsSize;
float boundsInnerRatio;
float boundsWeight;

[numthreads(64, 1, 1)]
void UpdateBoids(uint3 id : SV_DispatchThreadID)
{
    uint myIndex = id.x;
    if (myIndex >= numBoids)
    {
        return;
    }

    BoidData myBoid = boidsBuffer[myIndex];

    float3 separationForce = float3(0, 0, 0);
    float3 averageVelocity = float3(0, 0, 0);
    float3 center = float3(0, 0, 0);

    int separationCount = 0;
    int alignmentCount = 0;
    int cohesionCount = 0;

    for (uint i = 0; i < numBoids; i++)
    {
        if (i == myIndex)
        {
            continue;
        }

        BoidData otherBoid = boidsBuffer[i];
        float3 offset = myBoid.position - otherBoid.position;
        float sqrDistance = dot(offset, offset);

        // Seperation
        if (sqrDistance < separationDistanceSqr && sqrDistance > 0)
        {
            separationForce += offset / sqrDistance;
            separationCount++;
        }

        // Alignment
        if (sqrDistance < alignmentDistanceSqr)
        {
            averageVelocity += otherBoid.velocity;
            alignmentCount++;
        }

        // Cohesion
        if (sqrDistance < cohesionDistanceSqr)
        {
            center += otherBoid.position;
            cohesionCount++;
        }
    }

    float3 finalSteering = float3(0, 0, 0);

    if (separationCount > 0)
    {
        finalSteering += separationForce / separationCount * separationWeight;
    }

    if (alignmentCount > 0)
    {
        finalSteering += normalize(averageVelocity) * alignmentWeight;
    }

    if (cohesionCount > 0)
    {
        finalSteering += normalize(center / cohesionCount - myBoid.position) * cohesionWeight;
    }

    // Cubic Bounds Steer
    float3 extents = boundsSize * 0.5;
    float3 innerExtents = extents * boundsInnerRatio;
    float3 offsetBounds = myBoid.position - boundsCenter;

    float3 boundStrength = saturate((abs(offsetBounds) - innerExtents) / max(extents - innerExtents, 0.0001));
    finalSteering += -sign(offsetBounds) * boundStrength * boundsWeight;

    if (length(finalSteering) < 0.0001)
    {
        finalSteering = myBoid.forward;
    }

    float3 acceleration = normalize(finalSteering) * accelerationForce;
    float3 nextVelocity = myBoid.velocity + (acceleration * deltaTime);

    float speed = length(nextVelocity);
    myBoid.velocity = speed > myBoid.maxSpeed ? (nextVelocity / speed) * myBoid.maxSpeed : nextVelocity;

    float currentSpeed = min(speed, myBoid.maxSpeed);
    if (currentSpeed > 0.1)
    {
        float3 targetForward = myBoid.velocity / currentSpeed;

        float3 globalUp = float3(0, 1, 0);
        float3 right = normalize(cross(globalUp, targetForward));
        float lateralAcc = dot(acceleration, right);

        float rollAngle = lateralAcc * bankMultiplier * DEG2RAD;
        float3 targetUp = normalize(globalUp * cos(rollAngle) + right * sin(rollAngle));

        myBoid.forward = normalize(lerp(myBoid.forward, targetForward, deltaTime * rotationalSharpness));
        myBoid.up = normalize(lerp(myBoid.up, targetUp, deltaTime * rotationalSharpness));
    }

    myBoid.position += myBoid.velocity * deltaTime;

    boidsBuffer[myIndex] = myBoid;

    float3 fwd = normalize(myBoid.forward);
    float3 upDir = normalize(myBoid.up);
    float3 rightDir = normalize(cross(upDir, fwd));
    upDir = cross(fwd, rightDir);

    float4x4 o2w = float4x4(
        rightDir.x * boidScale, upDir.x * boidScale, fwd.x * boidScale, myBoid.position.x,
        rightDir.y * boidScale, upDir.y * boidScale, fwd.y * boidScale, myBoid.position.y,
        rightDir.z * boidScale, upDir.z * boidScale, fwd.z * boidScale, myBoid.position.z,
        0, 0, 0, 1
    );

    transformBuffer[myIndex] = o2w;
}
